import {
  MarketingShell,
  Section,
  Prose,
} from "@/components/marketing/MarketingShell";

export const metadata = {
  title: "Terms of service · PraxTalk",
  description:
    "Terms governing use of the PraxTalk customer messaging service.",
  alternates: { canonical: "/terms" },
};

const LAST_UPDATED = "May 3, 2026";

export default function TermsPage() {
  return (
    <MarketingShell
      eyebrow="Legal"
      title="Terms of service"
      description={`Last updated ${LAST_UPDATED}. By creating a PraxTalk workspace you agree to these terms.`}
    >
      <Section title="The service">
        <Prose>
          <p>
            PraxTalk is operated by Praxxii Global (Aligarh,
            India). The service is in <strong>open beta</strong>: features,
            pricing, and SLAs may change with reasonable notice.
          </p>
        </Prose>
      </Section>

      <Section title="Acceptable use">
        <Prose>
          <p>You may not use PraxTalk to:</p>
          <ul>
            <li>Send spam, phishing, or unsolicited bulk messages;</li>
            <li>
              Process special-category personal data (health, biometric,
              etc.) without a separately-signed BAA / DPA covering it;
            </li>
            <li>
              Reverse-engineer, abuse the API beyond documented rate
              limits, or interfere with other workspaces&apos; service;
            </li>
            <li>Build a competing product using our APIs.</li>
          </ul>
          <p>
            We may suspend or terminate workspaces that breach these
            limits, with notice where reasonable.
          </p>
        </Prose>
      </Section>

      <Section title="Your data">
        <Prose>
          <p>
            You retain ownership of every conversation, lead, and
            knowledge-base entry in your workspace. We process this data
            on your behalf as described in our{" "}
            <a href="/privacy">Privacy Policy</a>. The DPA at{" "}
            <a href="/dpa">/dpa</a> governs sub-processor obligations
            for B2B customers under GDPR Art. 28.
          </p>
        </Prose>
      </Section>

      <Section title="Billing">
        <Prose>
          <p>
            Paid plans bill monthly via PayPal or Razorpay. The free
            Spark tier carries no commitment. Upgrades take effect
            immediately; downgrades at the next billing cycle. Refunds
            are issued for genuine service failures (extended outages,
            data loss) on a pro-rata basis.
          </p>
        </Prose>
      </Section>

      <Section title="Beta-quality disclaimer">
        <Prose>
          <p>
            PraxTalk is provided &quot;as is&quot; during the open-beta
            period. Atlas AI replies are generated by language models and
            may be inaccurate; you are responsible for reviewing
            auto-replies before they go to your customers (use the
            confidence threshold and operator drafts mode if uncertain).
          </p>
        </Prose>
      </Section>

      <Section title="Liability">
        <Prose>
          <p>
            To the extent permitted by law, our aggregate liability
            under these terms is capped at the fees you paid in the
            twelve months preceding the claim. We exclude indirect,
            consequential, and lost-profits damages.
          </p>
        </Prose>
      </Section>

      <Section title="Termination">
        <Prose>
          <p>
            You can delete your workspace at any time from{" "}
            <a href="/app/billing">/app/billing</a>. Upon deletion we
            erase all workspace data within 90 days, except where
            retention is required by law.
          </p>
        </Prose>
      </Section>

      <Section title="Governing law">
        <Prose>
          <p>
            These terms are governed by the laws of India. Disputes
            will be resolved in the courts of Aligarh, Uttar Pradesh,
            unless overridden by the mandatory law of the customer&apos;s
            country.
          </p>
          <p className="text-sm italic text-muted">
            This is a starter draft and should be reviewed by qualified
            counsel before being relied upon. Last reviewed by Praxxii
            Global on {LAST_UPDATED}.
          </p>
        </Prose>
      </Section>
    </MarketingShell>
  );
}
